api-trading-env: ENC[AES256_GCM,data:q9YvBGvyV9Y1VOcTDIqtNKJscVKrpKKKP5kM1O+2S3qoznJ5j8bPtWe9daiiua4MXw0tyTFZBDMGIdwE7hiWp04Xjr94l858VaK2l7l629ogGvhuRzmWnhuF1mXQ6/7HQpp8LXX9DmyT3w9jkXeQJEAfIpcReV392mtK9jCTTrKMiUVOONioK5WWcvfWPeq5lNXpOqIqi4qcaREqm9bhu8CZoYH48801WrQMBn8nlsSYLld0TiMuoWU/9ouglOVXSng9KPLFaOVDgHU/PPxhDxL7HHU47c5OEz3le0NgMxaD0Mz1y6/31z0KBpmIKpEygmLlezERT0z9zZbsxMsyagxigbkIuAFQWw2Mks24pKOgxslI0S2NBgrcJCdsq+dFFhXVTlOZpmn69evhett3Tsl/o8KfpvDsEsE0gGVPB27I3oMgZndAstReRIMTl74rGVZDSTTSYZlTHyM0OB69XiKCw1QtG2PvtAl9XUSwsT3fZ3UW0YdXHt5sVE+jkblVsc5uwSDlZ9RL0QKS7VQiVECXj38m2upNbq2bWeU/B+nUK/uvQadicUSIzthUxaBKDEOPhjUzDB9LbiZ5h3I=,iv:H+TCUvhekaZmE6FqxiYvPtR1mEx/lNoL5MLBls9V5TU=,tag:In8L0sZJ4/g0mgzmpZWKdQ==,type:str]
bot-trading-env: ENC[AES256_GCM,data:gO+BrXnoJ9ZRXR/pvXfbUMA7unL+7dq1Z+LSDXp3a4z9RNd3GnHFZY0BQp8sbKY9sCg/X+vgWrOLw1u5NR2/J1AiCwOhy50xZurksNHiwJYNKkrM4YdVnd3ng7gGZIF6P/pwLzl7wF9znTJ2Wv6tQweEtcrTysEkxBGp72HiLZLKyhoFDy50VCW9ahQAs00PHvbFdD+6osYm+657faY+,iv:AoimpkaBXn69f9fPlPk52CbYbS0/3Mn0cF1RNVe4wHg=,tag:Ovr2Xewh/MwhAdwFmtXL2Q==,type:str]
web-trading-env: ENC[AES256_GCM,data:NUlGyEw0puvl01WoevggwqENz9DY/TqoMLopLV1BaUnvJ3ZMFR+BH9+abXKfrVKZe8lriFPW+RzX9alkgcY=,iv:kSEq8XUSjwjLPMF0Vey76FsRFtksV/ceMfwKpWsidJ4=,tag:43EW4F5Q0hV7/cQRHs/uQA==,type:str]
sops:
    age:
        - recipient: age1qe3jac9hdy5mlj5n3vp64gqc74euv4a8aazpwne447ytyah7xuwse026he
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYnE5WHl0c0crVmZiQWJH
            Tnl4YmJUSW96TEdQVGQ5dVFBblBCMVN5dUdZCm1pRlhzSlpEdmQzMVBDRzgvOVNp
            NjA3d3llSm9yY3M4czJoTzYyb3FYeXMKLS0tICtabVFSdjRvbGxvZnY0ck14NVU0
            YW9TNnNtT1M5UnJUZmRLd2poY1BNdmcK7wLUuw8k6glT0ZuD/mgFzaUl+9M1GRxy
            1VPz4i9KKsTz4LkvLlu2EMWVvjKwEEW/r8o77q+ZSqs55jcanLSwfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T06:53:55Z"
    mac: ENC[AES256_GCM,data:a9k1UbjFG2hHDFMG1MFozTth0wy4X5zdvbKtVtwFjZ/TlYMRrSQM9yfPWyzkhtLrJ9AWLrPWUj7PCaaNJ6P8+x70dkxHh8EhtSKf3Lf9KOMIbNTLnfhIVpHwGmYgyrt6fBkLKKbsMr9vDWJC/SSmbjslqDlTxjcmMuqn1soYLpA=,iv:EsA8pliDitiAhMrNVSCPwZNOYriHEojacpSfWywxlwo=,tag:5p4K1HO0NAEJkXSBLkMspw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
