jam-company-api: ENC[AES256_GCM,data:cNXvvJpGv2TWUuwVCqRwwaPTFWVVTedBDOY3unUOWpYTR91e4YPS/tJ4siRH0rSb97m6fieErX/HQ9zm96w7sWRqd+y46LtDgP+ssEPx3r+6X4/BMiuiHFNTB1tdGZYSbU1fn2WLEjiCd3GHmoIH9TDWGNbMRO6sspmt2FFLTL+BNUezAPNRQycNaPnMTiT3vqNj7oxn6iiFAHWIA8u+ddcdtNOTpt8xqKKdzWfGbCCFEC6EEEOvy8XR3YHfszNljymocnMr7rxSuYH3wU/0DnNn4inMCJl3kx863JhX2/DmhQ==,iv:szAQVGY6x+hLmN/tYDwG/uMz8U3GwJasv2XhIS0EAwo=,tag:7l/LIiJ+wdcZU0rbGZX5pQ==,type:str]
sops:
    age:
        - recipient: age1qe3jac9hdy5mlj5n3vp64gqc74euv4a8aazpwne447ytyah7xuwse026he
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS0ZvRU1QL0pBSFZqVy9C
            dHF0eDlPQkhBNWh1b3RZZHc5OGYvcTduZ2hvCmY3TkNiM251bi8rVFIyL1J5NWc1
            TG01VmRzMUVhcDhaR0hRdkNpL0J3NzgKLS0tIGhQT2RxTkRyT2NqbkJXajRJN2NN
            QXBFYkpCVFYvVndkWjRsWUdSdDliVVUK6HvPmUQgOGEtZLgQLkUHqX0nVwtZsuMT
            OFn7XEskBG+qGtEnqe3WSwp/uUAdUgmZ1M+LYW86b3RGG9btX2iM6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-06T10:15:05Z"
    mac: ENC[AES256_GCM,data:IJA7QJQoA5EyWwpmacW9fj14YyaO3p0hdRh8ALuERYySTwE8Ip0Noy0pghoD0EUkThwtZdTni6dnk8vvYS+sLdMImiehM6H4vW8zC6PEjGp2uhRGBIzCd/D2GlsC6mukKhNI6yzKxuTqDQK79KER/sikF5b4rCmHSdwHAcqlsmY=,iv:afX0ZK+6fpUxU4BTneiTRMSrH7R41eTqMyGsDhJzbA4=,tag:SPpYkFpqA7V82DqPhrPVyw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
