jam-company-api: ENC[AES256_GCM,data:mdD+x4vC/STnLj2Y2lXqPmlEGQlxZoqGL97RYtqy2cBxN5IusL7Ku18CPq1IRN8/2Cab6o1XS3ENTx0Tt5Q7xAKtdq9DlevVUonp1XWhJHXM/i85M6yN53O8mnDKBqYN56eR1iayHYJ5Hkq4y69CGqPdPCe78843yeNdLEW047qo0ElwjVSmRqwAXZ0HR6Kt9UxiWsLl1L3jY21Ip7NCuRsMoYU/q25o1Xx0uAs89uNBlzzY6jOB3wAIYDeYL60G/JYn1KF2aybotxxnTD7LFAFF1qUHwO1I,iv:r7mS6qT4+uH+RH+l0ZjyXxFNf11DI+dnlfy6wLCDR1c=,tag:7u8uBpnWPnipCvEaHw53UA==,type:str]
sops:
    age:
        - recipient: age1qe3jac9hdy5mlj5n3vp64gqc74euv4a8aazpwne447ytyah7xuwse026he
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS0ZvRU1QL0pBSFZqVy9C
            dHF0eDlPQkhBNWh1b3RZZHc5OGYvcTduZ2hvCmY3TkNiM251bi8rVFIyL1J5NWc1
            TG01VmRzMUVhcDhaR0hRdkNpL0J3NzgKLS0tIGhQT2RxTkRyT2NqbkJXajRJN2NN
            QXBFYkpCVFYvVndkWjRsWUdSdDliVVUK6HvPmUQgOGEtZLgQLkUHqX0nVwtZsuMT
            OFn7XEskBG+qGtEnqe3WSwp/uUAdUgmZ1M+LYW86b3RGG9btX2iM6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T10:33:05Z"
    mac: ENC[AES256_GCM,data:ViX1bK1PXTV2vw9r/9FIqm4hWiXlOsXvTKl35dUxQyf4cyYzuB7rKdzpqesat2yWDz/E2ZRVNtFEhB2CCUyG/4s8MRuQLW8uJL6P288zZzQpWEfIoHQakownqX7xBwNVTZHBQKlHyApo7VdKxau/kcECCwhV6hR4UtH1SLsPDlc=,iv:4qS2a8uKDLJgoq1pKkyKY1C0pIcj5Sg8ofITRlytZC4=,tag:2S2LDsd7zk0eRnvd+KOw1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
