api-trading-env: ENC[AES256_GCM,data:sUxeLiHzoXDxK1TDR2mLB8uFUA9EObE4jZIj3eHXh5TBTaU1WZ87srnR4qWLl4zr4+zb6+2dItTfklCVpvDtYO0dDinyx6SnZR/rXFteH+xrjUXx3s/JBz6kp7Fr9HyffYJrpy0VloTckNaDysgTXgSLIYy/9u5XSDEzjEd52Uk2FUXzUN31VpCLYZxwIbSJomQQav1aNdJZmk7cD52l/G+4pWxXcO2qRoJvSVdVOA++zYik569atIU0CHatTlQvxP0lsp5EWln9k+SqrrXNDksRY1bK6HIdiir1v2gFVs7YdmDHcWUj5DZZDeDASkhbMC+AzBKZscAffp2oao+VHB4+sMUjFCBukDlJ8WMoxmmFNTVFwio+yl56LKpfWrhrIrJsoc2IX1PcfjJam49C9VMTK0RtkuFKsMo9IBYtaS3s53JRXplIHykki9hKBThUiPi7pwsHLx0MNfq8Je1W1uV1vjsSlWcvjeRHFid7+lzGanXAIJhqfwJVlj0lE6bloa0dQoSRqhFF53Gw,iv:AQpVmppshmvY7a/b0UKKGJ2P6YA9tYFBYK1eD697w8Y=,tag:3d9OfE6lF4xkz4u8NqBikg==,type:str]
bot-trading-env: ENC[AES256_GCM,data:DFB7v3AW4pOWIke+DJXlf40sC6ajteWK8R6nkv/cD+9VSg==,iv:SsOH50CB5yw9uDNxYYUNKvjHceZNWHJE/uDw5s0fBFA=,tag:XDucMcZSEmFvpDpcMzTbiQ==,type:str]
web-trading-env: ENC[AES256_GCM,data:aVC0/N8e8eDRSAVevdLbQQRU7iIZNINaTGeyHxN7,iv:eEla8zgupQhAv8vwoafF+X72Omu6YhEp6XFEMuJabTM=,tag:2V53ZYzkDOZ0FmIgQLFN5w==,type:str]
sops:
    age:
        - recipient: age1qe3jac9hdy5mlj5n3vp64gqc74euv4a8aazpwne447ytyah7xuwse026he
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYnE5WHl0c0crVmZiQWJH
            Tnl4YmJUSW96TEdQVGQ5dVFBblBCMVN5dUdZCm1pRlhzSlpEdmQzMVBDRzgvOVNp
            NjA3d3llSm9yY3M4czJoTzYyb3FYeXMKLS0tICtabVFSdjRvbGxvZnY0ck14NVU0
            YW9TNnNtT1M5UnJUZmRLd2poY1BNdmcK7wLUuw8k6glT0ZuD/mgFzaUl+9M1GRxy
            1VPz4i9KKsTz4LkvLlu2EMWVvjKwEEW/r8o77q+ZSqs55jcanLSwfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T11:25:56Z"
    mac: ENC[AES256_GCM,data:Tf7a2fBGKWJwRpcdX0d0MkBfc9acvC+Zb/wfHWl3gXH8L3M2n1qnfjNtownAFyCgz7iwOt4BE5ujdYcw6efiQsIlSbPS0vAiydmcXmm7T4U42x5bF/3FsaBA0xw9s/ILCVRw1+j/oU5wZuj9Xi5vanWI//yguBtBhVtcxsZhJXo=,iv:vuBzTwNNzg8IXxm8IUQahsWEDnRYn+KAZzW5k8/1Ouw=,tag:C/DoBt0e4n7YcgTRTigoQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
